In [ ]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji is papu',
		'inquilab zindabad']

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts(docs)

In [ ]:
len(tokenizer.word_index)

19

In [ ]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[7, 1],
 [1, 1],
 [3, 3, 8],
 [2, 9, 2, 1, 2],
 [10, 11, 12, 13],
 [4, 4],
 [5, 5],
 [6, 6],
 [14, 15, 16, 17],
 [18, 19]]

In [ ]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')

In [ ]:
sequences

array([[ 7,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3,  8,  0,  0],
       [ 2,  9,  2,  1,  2],
       [10, 11, 12, 13,  0],
       [ 4,  4,  0,  0,  0],
       [ 5,  5,  0,  0,  0],
       [ 6,  6,  0,  0,  0],
       [14, 15, 16, 17,  0],
       [18, 19,  0,  0,  0]], dtype=int32)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

model = Sequential()
model.add(Embedding(len(tokenizer.word_index) + 1, output_dim=2))
model.build(input_shape=(None, sequences.shape[1]))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 5, 2)           │            40 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 40 (160.00 B)

 Trainable params: 40 (160.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile('adam','accuracy')

In [ ]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
[[[-0.03003579 -0.02865094]
  [-0.03492359  0.00850846]
  [-0.03269317 -0.04116577]
  [-0.03269317 -0.04116577]
  [-0.03269317 -0.04116577]]

 [[-0.03492359  0.00850846]
  [-0.03492359  0.00850846]
  [-0.03269317 -0.04116577]
  [-0.03269317 -0.04116577]
  [-0.03269317 -0.04116577]]

 [[-0.01104603  0.03563353]
  [-0.01104603  0.03563353]
  [ 0.04832791 -0.0177717 ]
  [-0.03269317 -0.04116577]
  [-0.03269317 -0.04116577]]

 [[ 0.03522639  0.02701141]
  [ 0.00166701 -0.03886919]
  [ 0.03522639  0.02701141]
  [-0.03492359  0.00850846]
  [ 0.03522639  0.02701141]]

 [[ 0.03071512 -0.02362597]
  [-0.00649227  0.0215273 ]
  [-0.02358797  0.00114554]
  [ 0.03323021 -0.03042425]
  [-0.03269317 -0.04116577]]

 [[-0.01863573  0.0192993 ]
  [-0.01863573  0.0192993 ]
  [-0.03269317 -0.04116577]
  [-0.03269317 -0.04116577]
  [-0.03269317 -0.04116577]]

 [[-0.03636979  0.04266802]
  [-0.03636979  0.04266802]
  [-0.03269317 -0.04116577]
  [-0.03269317 -0.04116577

In [ ]:
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [ ]:
(X_train,y_train),(X_test,y_test) = imdb.load_data(num_words=10000)
import numpy as np
y_train = np.array(y_train).astype('float32')
y_test = np.array(y_test).astype('float32')

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


In [ ]:
X_train = pad_sequences(X_train,padding='post',maxlen=50, dtype='int32')
X_test = pad_sequences(X_test,padding='post',maxlen=50, dtype='int32')

In [ ]:
X_train.shape

(25000, 50)

In [ ]:
model = Sequential()
model.add(Embedding(10000, 2))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))
model.build(input_shape=(None, 50))
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 50, 2)          │        20,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

In [ ]:
model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - acc: 0.6616 - loss: 0.5858 - val_acc: 0.7902 - val_loss: 0.4567
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - acc: 0.8312 - loss: 0.3883 - val_acc: 0.8098 - val_loss: 0.4170
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - acc: 0.8664 - loss: 0.3233 - val_acc: 0.8090 - val_loss: 0.4237
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - acc: 0.8857 - loss: 0.2877 - val_acc: 0.8038 - val_loss: 0.4387
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - acc: 0.8996 - loss: 0.2559 - val_acc: 0.7894 - val_loss: 0.4893
